spring.application.name=spring-boot-demo


spring.datasource.url=jdbc:mysql://localhost:3306/ajuba
spring.datasource.username=root
spring.datasource.password=Nive@07
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

